### ISSUE TITLE
ZipException when running a match

### ISSUE THREAD

**Issue by Sheljohn** [battlecode/battlecode-scaffold-2017#21]
I am having troubles running a match with the client. 

I downloaded the latest version of battlecode, and built it from the terminal using `gradle build`. I have looked at the FAQ for information but could not find any entry about a ZipException, and to confirm the versions/environment:

```
$ gradle --version
------------------------------------------------------------
Gradle 3.3
------------------------------------------------------------

Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.11.6 x86_64

$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
```

The build completes successfully from the command line, and I can open the client application, but when I try running a match, I get an error message about a ZipException. Unfortunately I don't seem to be able to copy/paste it (and I don't know where to look for logs), but I took a screenshot of the error which you can view [here](http://pasteboard.co/m5nFk0SmK.png).

**Comment by Sheljohn** [comment]
Following up on this, trying to use `./gradlew build` instead, I get an error from the command line which I think is the same one:

```
Unzipping /Users/jhadida/.gradle/wrapper/dists/gradle-3.3-bin/64bhckfm0iuu9gap9hg3r7ev2/gradle-3.3-bin.zip to /Users/jhadida/.gradle/wrapper/dists/gradle-3.3-bin/64bhckfm0iuu9gap9hg3r7ev2
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by Sheljohn** [comment]
I think I "solved" this. 

I had gradle installed with Homebrew on my machine, but uninstalling it and letting `gradlew` download it automatically from `https://services.gradle.org/distributions/gradle-3.3-bin.zip` seems to have solved the problem. I can now run matches without issue.
